### PR TITLE
[Fix] Fixing logic around string matching and new tests

### LINKED ISSUE #21: Registering/Unregistering sibling nodes that start with the same string causes issues
**Describe the bug**
Internal LRUD state uses string paths to determine some of its logic.

The processes around these is broken if 2 siblings start with the same series of characters

**To Reproduce**

```js

nav.registerNode('root');
nav.registerNode('brand');
nav.registerNode('brand-content');

nav.unregisterNode('brand');
```

After this unregister call, `brand-content` is still inside the tree, but a call to `getNode('brand-content')` will return `undefined`, as its been removed from internal state.

**Expected behavior**
An unregister should not break internal state around pathing.

### PR DESCRIPTION
**Pull request by thomascgray**
## Description
We had some wonky logic around string matching when handling internal pathing.

This has been fixed.

## Motivation and Context
Fixes #21 

## How Has This Been Tested?
New tests

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -245,14 +245,11 @@ export class Lrud {
...
-      return !(nodeIdPath.includes('.' + nodeId))
+      return !nodeIdPath.includes(path + '.children.')
     })
 
     // if the node we're unregistering was focusable, we need to remove it from
-    // our focusableNodePathList
-    this.focusableNodePathList = this.focusableNodePathList.filter(nodeIdPath => {
-      return !(nodeIdPath.includes('.' + nodeId))
-    })
+    this.focusableNodePathList.splice(this.focusableNodePathList.indexOf(path), 1)
```
Comment (jordanholt) [inline src/index.ts]: Is the `path` guaranteed to be in the `focusableNodePathList` at this point?

Comment (thomascgray) [reply src/index.ts]: Ooh, excellent catch. This should actually be wrapped in a check to ensure the node is focusable before we remove it from this array. Making the change now, 11/10 spot

Comment (thomascgray) [reply src/index.ts]: Actually, I think you've spotted some deeper broken logic around the `focusableNodePathList`. Will get some more tests added.

Comment (thomascgray) [reply src/index.ts]: Fixes pushed.

**Comment by thomascgray** [comment]
@jordanholt excellent spot - I've done more some fixes and added a new test ensures both path lists are consistent when unregistering a node that has focusable children
