### PR TITLE
[Fix] Assigning focus, and moving over/to branches without focusable children

### LINKED ISSUE #26: Empty nodes cause problems when trying to focus/navigate
**Describe the bug**
When a node contains no focusable items, LRUD throws an error when trying to find an appropriate focusable item.

### Case 1 - initial focus
**To Reproduce**
```
const nav = new Lrud()

nav.registerNode('root', {
  orientation: 'vertical'
})

nav.registerNode('node1', {
  orientation: 'horizontal',
  parent: 'root'
})

nav.registerNode('node2', {
  orientation: 'horizontal',
  parent: 'root'
})

nav.register('item2', {
  parent: 'node2',
  selectAction: {}
})

nav.assignFocus('root')
```

**Expected behavior**
Should focus on `item2` but instead throws error:
`Uncaught TypeError: Cannot read property 'id' of undefined`

### Case 2 - moving to empty node
**To Reproduce**
```
const nav = new Lrud()

nav.registerNode('root', {
  orientation: 'vertical'
})

nav.registerNode('node1', {
  orientation: 'horizontal',
  parent: 'root'
})

nav.registerNode('node2', {
  orientation: 'horizontal',
  parent: 'root'
})

nav.register('item1', {
  parent: 'node1',
  selectAction: {}
})

nav.assignFocus('root')

nav.handleKeyEvent({ direction: 'down' })
```

**Expected behavior**
Should remain focused  on `item1` but instead throws error:
`Uncaught TypeError: Cannot read property 'id' of undefined`

### Case 3 - moving past empty node to item beyond it
**To Reproduce**
```
const nav = new Lrud()

nav.registerNode('root', {
  orientation: 'vertical'
})

nav.registerNode('node1', {
  orientation: 'horizontal',
  parent: 'root'
})

nav.registerNode('node2', {
  orientation: 'horizontal',
  parent: 'root'
})

nav.registerNode('node3', {
  orientation: 'horizontal',
  parent: 'root'
})

nav.register('item1', {
  parent: 'node1',
  selectAction: {}
})

nav.register('item3', {
  parent: 'node3',
  selectAction: {}
})

nav.assignFocus('root')

nav.handleKeyEvent({ direction: 'down' })
```

**Expected behavior**
Should focus  on `item3` but instead throws error:
`Uncaught TypeError: Cannot read property 'id' of undefined`

### PR DESCRIPTION
**Pull request by thomascgray**
## Description

Ensures 2 things happen

- if assigning focus to a node with children, but 0 focusable children, throw an exception
- if digging down from a node that is not focusable, and has 0 focusable children, instead dig down from its next sibling

This ensures that actions that would result in focus trying to be set on something invalid either don't happen, or can be caught properly.

I've also done minor fixes in place around typescript

- added return type to `getNode()`
- added types to interface for node

## Motivation and Context
Fixes #26 

## How Has This Been Tested?
New unit tests

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -492,18 +492,25 @@ export class Lrud {
...
     if (!node.activeChild) {
       node.activeChild = this.getNodeFirstChild(node).id
     }
 
-    const activeChild = node.children[node.activeChild]
-
-    if (isNodeFocusable(activeChild)) {
-      return activeChild
-    }
+    let nextChild = node.children[node.activeChild]
```
Comment (benwdev) [inline src/index.ts]: What happens if there is no first child in this instance?

Comment (benwdev) [reply src/index.ts]: Ah think this in answered in the next line!

Comment (thomascgray) [reply src/index.ts]: Haha, yep - the next line is a clause around "if `nextChild` is not focusable, dig down again from `nextChild`"

And `digDown()` itself takes care of an invalid node in that case.
